name: app_ta
description: "A Flutter app with integrated Wordly game."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.4
  intl: ^0.18.0
  # Common packages
  http: ^1.3.0
  path_provider: ^2.1.5

  # Wordly game packages
  bloc: ^9.0.0
  clock: any
  collection: any
  flutter_bloc: ^9.1.0
  flutter_colorpicker: ^1.1.0
  freezed_annotation: ^3.0.0
  meta: any
  package_info_plus: ^8.3.0
  path: any
  rxdart: ^0.28.0
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  stack_trace: any
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  freezed: ^3.0.2
  carapacik_lints: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/dictionary/
    - assets/fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 120

flutter_intl:
  enabled: false
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/src/core/constant/localization/translations
  output_dir: lib/src/core/constant/localization/generated

flutter_launcher_icons:
  image_path_android: "assets/images/icon-1024x1024.png"
  image_path_ios: "assets/images/icon-borderless-1024x1024.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/images/icon-background-1024x1024.png"
  adaptive_icon_foreground: "assets/images/icon-foreground-1024x1024.png"
  min_sdk_android: 24
  web:
    generate: true
    image_path: "assets/images/icon-foreground-1024x1024.png"
    background_color: "#FFFFFF"
  macos:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
  windows:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    icon_size: 256